In [1]:
import numpy as np

sleep = np.loadtxt('data/sleep.csv', skiprows=1, delimiter=',')
print(sleep)

[[34.  3. 63. ... 19.  2.  2.]
 [ 5.  2. 68. ... 17.  1.  1.]
 [65.  2. 60. ... 11.  2.  3.]
 ...
 [ 7.  0. 46. ... 13.  1.  2.]
 [52.  2. 53. ... 15.  6.  3.]
 [45.  2. 63. ... 15.  7.  2.]]


In [2]:
# ask some question to the numpy array 
sleep.shape

(1467, 9)

In [4]:
# printing average excercise per minute 
print(f' Average excercise per minute {np.average(sleep[:, 0])}')
sleep[:, 0]

 Average excercise per minute 41.80299931833674


array([34.,  5., 65., ...,  7., 52., 45.])

In [6]:
# max sleep rating. 
print(np.max(sleep[:, 8]))
print(np.min(sleep[:, 8]))

4.0
1.0


In [11]:
no_coffee = sleep[sleep[:, 1] == 0]
no_coffee
print(np.average(no_coffee[:, 8]))
with_coffee = sleep[sleep[:, 1] == 3]
print(np.average(with_coffee[:, 8]))



2.713467048710602
2.2808398950131235


In [22]:
# max coffee 

max_coffee = np.max(sleep[:, 1])
min_coffee = np.min(sleep[:, 1])
print(max_coffee, min_coffee)
for x in range(int(min_coffee), int(max_coffee) + 1):
    x_coffee = sleep[sleep[:, 1] == x]
    print(x, np.average(x_coffee[:, 8]))
    np.savetxt('data/sleep2.csv', x_coffee, delimiter=',',
               header='Excercise in min , Coffees, Av', fmt='%d')

3.0 0.0
0 2.713467048710602
1 2.5726256983240225
2 2.4564643799472297
3 2.2808398950131235
