# Numpy
we have list in python which is slow . so numpy was built which has various inbuilt functions mathematically for datascience


In [2]:
# importing numpy and giving it a short alias to access 
import numpy as np 

In [5]:

# the array type is called ndarray 
arr=np.array([1,5,3,4,2])

print(arr)
print(type(arr))
#printing the numpy version
print(np.__version__)

b = arr[:2]
print(b)

[1 5 3 4 2]
<class 'numpy.ndarray'>
1.18.5
[1 5]


In [6]:
# creating ndarray from list
list=[4,2,3]
np_array = np.array(list)
print(np_array)

[4 2 3]


In [13]:
# 0 dimension array
arr=np.array(90)
print(arr.ndim)

arr1=np.array([4,3,2,1])
print(arr1.ndim)

# 2 dimension array . an array containing 1d arary as element
arr2=np.array([[2,3,5],[4,5,6]])
print(arr2.ndim)

#3d array contains 2d array as its elements
arr3 = np.array([arr2])
print(arr3.ndim)

0
1
2
3


In [16]:
# create an array of higher dimention 
arr=np.array([1,2,3,4],ndmin=5)
print(arr.ndim)
print(arr)

5
[[[[[1 2 3 4]]]]]


In [4]:
# creating arrays with 10 zeros . this defaults to float datatype
np.zeros(10)
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# to create int data type we have to give dtype = int 
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
np.random.randint(1,200,10)
# half open range . this means, inclusive of 1 and exclusive of 200 

array([154,  42, 140, 185,  90, 139, 150, 153,  47, 190])

In [8]:
[x for x in range(1,10)] 

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
# 2d array using np

np.array([[1,2,3],[3,4,5],[5,6,7]])

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [18]:
np.arange(64).reshape(4,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [26]:
t = np.arange(100).reshape(10,10)
t

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
r = np.random.random((10,10))
r

array([[0.45959394, 0.06443347, 0.38754944, 0.02957397, 0.82122169,
        0.46994623, 0.673437  , 0.0562063 , 0.08827707, 0.00821442],
       [0.60109037, 0.96360863, 0.3863763 , 0.46964958, 0.26676063,
        0.66170309, 0.59657592, 0.88421628, 0.45924907, 0.99745228],
       [0.96396048, 0.44264792, 0.05699574, 0.7558403 , 0.00115728,
        0.84170968, 0.30396235, 0.44731898, 0.34059742, 0.35158016],
       [0.44672187, 0.61118723, 0.59602994, 0.35895676, 0.60384879,
        0.18457721, 0.91086676, 0.98743949, 0.51384035, 0.63623834],
       [0.72628902, 0.54669947, 0.86372245, 0.60054162, 0.98515446,
        0.14488214, 0.05267655, 0.99044519, 0.99563153, 0.22138327],
       [0.47977442, 0.7470384 , 0.52754092, 0.61697516, 0.7096678 ,
        0.27980918, 0.25838593, 0.30467858, 0.05122876, 0.26434954],
       [0.60701735, 0.9881271 , 0.8814596 , 0.63184856, 0.53983624,
        0.09454407, 0.51179171, 0.41328057, 0.79358801, 0.36681275],
       [0.23143472, 0.13863444, 0.7992361

In [27]:
print(t[r>0.5])

[ 4  6 10 11 15 16 17 19 20 23 25 31 32 34 36 37 38 39 40 41 42 43 44 47
 48 51 52 53 54 60 61 62 63 64 66 68 72 74 76 79 80 82 83 84 86 88 91 92
 95 97]
