# Numpy
we have list in python which is slow . so numpy was built which has various inbuilt functions mathematically for datascience


In [5]:
# importing numpy and giving it a short alias to access 
import numpy as np 
# the array type is called ndarray 
arr=np.array([1,5,3,4,2])

print(arr)
print(type(arr))
#printing the numpy version
print(np.__version__)

b = arr[:2]
print(b)

[1 5 3 4 2]
<class 'numpy.ndarray'>
1.18.5
[1 5]


In [6]:
# creating ndarray from list
list=[4,2,3]
np_array = np.array(list)
print(np_array)

[4 2 3]


In [13]:
# 0 dimension array
arr=np.array(90)
print(arr.ndim)

arr1=np.array([4,3,2,1])
print(arr1.ndim)

# 2 dimension array . an array containing 1d arary as element
arr2=np.array([[2,3,5],[4,5,6]])
print(arr2.ndim)

#3d array contains 2d array as its elements
arr3 = np.array([arr2])
print(arr3.ndim)

0
1
2
3


In [16]:
# create an array of higher dimention 
arr=np.array([1,2,3,4],ndmin=5)
print(arr.ndim)
print(arr)

5
[[[[[1 2 3 4]]]]]
